// front/components/MainEditor.vue
<script setup lang="ts">
import type { Editor, JSONContent } from '@tiptap/core';
import { EditorContent } from '@tiptap/vue-3';
import { BubbleMenu } from '@tiptap/vue-3/menus';
import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  Crop,
  FileText,
  Plus,
  RotateCw,
  Share,
  Trash2,
  X,
} from 'lucide-vue-next';
import { toast } from 'vue-sonner';
import { Badge } from '~/components/ui/badge';
import { Button } from '~/components/ui/button';
import { Skeleton } from '~/components/ui/skeleton';
import type { Note } from '~/types/notes';
import { normalizeUploadedImageUrl, stripHtml } from '~/utils/notes';

const props = withDefaults(defineProps<{
  note?: Note | null;
  isPending?: boolean;
}>(), {
  note: undefined,
  isPending: false,
});

const emit = defineEmits<{
  save: [note: { title: string; content: JSONContent; tags?: string[]; folderId?: string | null }];
  delete: [];
}>();

const config = useRuntimeConfig();
const fileInputRef = ref<HTMLInputElement | null>(null);
const cropImageInfo = ref<{ src: string; file: File } | null>(null);
const isTagComposerOpen = ref(false);
const deleteDialogOpen = ref(false);

const { data: folders } = useFolders();
const { data: availableTags } = useTags();
const {
  editor,
  title,
  tags,
  tagInput,
  folderId,
  saveStatus,
  handleTitleChange,
  handleTagInputChange,
  handleAddTag,
  handleRemoveTag,
  handleFolderChange,
  handleFileUpload,
  handleCrop,
  handleRotate,
} = useNoteEditor({
  note: toRef(props, 'note'),
  isPending: toRef(props, 'isPending'),
  onSave: (data) => emit('save', data),
});

const createdAtDate = computed(() => props.note?.createdAt ? new Date(props.note.createdAt) : null);
const createdAtLabel = computed(() => {
  if (!createdAtDate.value) return 'Draft';

  return createdAtDate.value.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
});
const selectedFolder = computed(() => (folders.value ?? []).find((folder) => folder.id === folderId.value) ?? null);
const pageTitle = computed(() => title.value.trim() || (props.note === null ? 'New note' : 'Untitled'));
const editorText = computed(() => editor.value?.getText() ?? stripHtml(props.note?.content ?? ''));
const wordCount = computed(() => editorText.value.trim() ? editorText.value.trim().split(/\s+/).length : 0);
const shouldShowImageMenu = ({ editor }: { editor: Editor }) => editor.isActive('image');

watch(() => props.note?.id, () => {
  isTagComposerOpen.value = false;
});

function commitTagComposer(rawTagInput = tagInput.value) {
  const didAddTag = handleAddTag(rawTagInput);
  isTagComposerOpen.value = false;
  return didAddTag;
}

function cancelTagComposer() {
  handleTagInputChange('');
  isTagComposerOpen.value = false;
}

function getAbsoluteImageUrl(src: string) {
  let fullUrl = normalizeUploadedImageUrl(src.split('?')[0]);
  if (!fullUrl.startsWith('http')) {
    const baseUrl = String(config.public.apiUrl || 'http://localhost:3001').replace(/\/$/, '');
    fullUrl = `${baseUrl}${fullUrl.startsWith('/') ? '' : '/'}${fullUrl}`;
  }
  return fullUrl;
}

async function getSelectedImageFile(filename: string) {
  if (!editor.value) return null;

  const attrs = editor.value.getAttributes('image');
  if (!attrs.src) return null;

  const response = await fetch(getAbsoluteImageUrl(attrs.src));
  const blob = await response.blob();
  return {
    src: attrs.src,
    file: new File([blob], filename, { type: blob.type }),
  };
}

async function startRotate(degrees: number) {
  if (!editor.value || saveStatus.value === 'rotating' || saveStatus.value === 'saving') return;

  try {
    const image = await getSelectedImageFile('image-to-rotate.webp');
    if (image) void handleRotate(image.file, degrees);
  } catch (error) {
    toast.error('Failed to fetch image for rotating', {
      description: error instanceof Error ? error.message : undefined,
    });
  }
}

async function startCrop() {
  if (!editor.value) return;

  try {
    cropImageInfo.value = await getSelectedImageFile('image-to-crop.webp');
  } catch (error) {
    toast.error('Failed to fetch image for cropping', {
      description: error instanceof Error ? error.message : undefined,
    });
  }
}

function confirmDelete() {
  deleteDialogOpen.value = false;
  emit('delete');
}
</script>

<template>
  <div v-if="note === undefined" class="flex h-full min-h-0 flex-col">
    <div class="space-y-3 border-b p-4 md:p-6">
      <Skeleton class="h-5 w-40" />
      <Skeleton class="h-9 w-full max-w-xl" />
    </div>
    <div class="mx-auto w-full max-w-4xl flex-1 space-y-4 p-4 md:p-8">
      <Skeleton class="h-12 w-3/4" />
      <Skeleton class="h-5 w-56" />
      <Skeleton class="h-80 w-full" />
    </div>
  </div>

  <div v-else class="flex h-full min-h-0 flex-col bg-background">
    <header class="shrink-0 border-b bg-background">
      <div class="flex flex-col gap-3 px-4 py-3 md:px-6">
        <div class="flex flex-wrap items-center gap-3">
          <div class="min-w-0 flex-1">
            <div class="flex items-center gap-2 font-mono text-[11px] uppercase tracking-wide text-muted-foreground">
              <NuxtLink to="/" class="hover:text-foreground">Notes</NuxtLink>
              <span>/</span>
              <span class="truncate">{{ pageTitle }}</span>
            </div>
            <h1 class="mt-1 truncate text-lg font-semibold tracking-tight">
              {{ pageTitle }}
            </h1>
          </div>

          <StatusBadge :status="saveStatus" :created-at="note?.createdAt" :updated-at="note?.updatedAt" />

          <div class="flex items-center gap-1">
            <Button variant="ghost" size="icon" title="Share">
              <Share class="size-4" />
            </Button>
            <Button
              v-if="note"
              variant="ghost"
              size="icon"
              title="Delete"
              @click="deleteDialogOpen = true"
            >
              <Trash2 class="size-4" />
            </Button>
          </div>
        </div>

        <EditorToolbar :editor="editor" @add-image="fileInputRef?.click()" />
      </div>
    </header>

    <main class="min-h-0 flex-1 overflow-y-auto scrollbar-thin">
      <div class="mx-auto w-full max-w-4xl px-4 py-6 md:px-8 md:py-10">
        <div class="mb-5 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
          <span class="font-mono">{{ createdAtLabel }}</span>
          <span class="h-1 w-1 rounded-full bg-muted-foreground/60" />
          <span>{{ wordCount }} words</span>
        </div>

        <input
          type="text"
          placeholder="Untitled"
          :value="title"
          class="mb-4 w-full bg-transparent text-4xl font-semibold tracking-tight outline-none placeholder:text-muted-foreground md:text-5xl"
          @input="handleTitleChange(($event.target as HTMLInputElement).value)"
          @keydown.enter.prevent="editor?.commands.focus()"
        >

        <div class="mb-8 flex flex-wrap items-center gap-2">
          <FolderPicker
            :folders="folders ?? []"
            :model-value="folderId"
            @update:model-value="handleFolderChange"
          />

          <button
            v-for="tag in tags"
            :key="tag"
            type="button"
            :title="`Remove #${tag}`"
            @click="handleRemoveTag(tag)"
          >
            <Badge variant="secondary" class="gap-1.5">
              #{{ tag }}
              <X class="size-3" />
            </Badge>
          </button>

          <TagSuggestionInput
            v-if="isTagComposerOpen"
            :available-tags="availableTags ?? []"
            :selected-tags="tags"
            :model-value="tagInput"
            @update:model-value="handleTagInputChange"
            @add="commitTagComposer"
            @cancel="cancelTagComposer"
          />

          <Button v-else variant="outline" size="sm" @click="isTagComposerOpen = true">
            <Plus class="size-4" />
            Tag
          </Button>
        </div>

        <div class="min-h-[58vh]">
          <BubbleMenu
            v-if="editor"
            :editor="editor"
            :should-show="shouldShowImageMenu"
          >
            <div class="flex items-center gap-1 rounded-md border bg-popover p-1 text-popover-foreground shadow-lg">
              <Button
                variant="ghost"
                size="icon"
                title="Align left"
                :class="editor.isActive({ textAlign: 'left' }) ? 'bg-accent' : ''"
                @click="editor.chain().focus().setTextAlign('left').run()"
              >
                <AlignLeft class="size-4" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                title="Align center"
                :class="editor.isActive({ textAlign: 'center' }) ? 'bg-accent' : ''"
                @click="editor.chain().focus().setTextAlign('center').run()"
              >
                <AlignCenter class="size-4" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                title="Align right"
                :class="editor.isActive({ textAlign: 'right' }) ? 'bg-accent' : ''"
                @click="editor.chain().focus().setTextAlign('right').run()"
              >
                <AlignRight class="size-4" />
              </Button>
              <div class="mx-1 h-5 w-px bg-border" />
              <Button variant="ghost" size="icon" title="Rotate 90 degrees" @click="startRotate(90)">
                <RotateCw class="size-4" />
              </Button>
              <Button variant="ghost" size="icon" title="Crop image" @click="startCrop">
                <Crop class="size-4" />
              </Button>
            </div>
          </BubbleMenu>

          <EditorContent :editor="editor" />

          <EmptyState
            v-if="!editor"
            :icon="FileText"
            title="Editor unavailable"
            description="The editor could not initialize in this session."
          />
        </div>
      </div>
    </main>

    <EditorStatusBar :folder-name="selectedFolder?.name" :tags="tags" :word-count="wordCount" />

    <ImageCropModal
      v-if="cropImageInfo"
      :image-url="cropImageInfo.src"
      @cancel="cropImageInfo = null"
      @crop="(pixelCrop) => { if (cropImageInfo) handleCrop(cropImageInfo.file, pixelCrop); cropImageInfo = null; }"
    />

    <Teleport to="body">
      <div
        v-if="deleteDialogOpen"
        class="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4 backdrop-blur-sm"
        @click.self="deleteDialogOpen = false"
      >
        <div class="w-full max-w-md rounded-lg border bg-popover p-6 text-popover-foreground shadow-xl">
          <div class="space-y-2">
            <h2 class="text-lg font-semibold">Delete this note?</h2>
            <p class="text-sm text-muted-foreground">
              The note will move to trash and can be restored later.
            </p>
          </div>
          <div class="mt-6 flex justify-end gap-2">
            <Button variant="ghost" @click="deleteDialogOpen = false">
              Cancel
            </Button>
            <Button variant="destructive" @click="confirmDelete">
              Delete
            </Button>
          </div>
        </div>
      </div>
    </Teleport>

    <input
      ref="fileInputRef"
      type="file"
      class="hidden"
      accept="image/*"
      @change="(event) => {
        const input = event.target as HTMLInputElement;
        const file = input.files?.[0];
        if (file) handleFileUpload(file);
        input.value = '';
      }"
    >
  </div>
</template>

// front/src/components/MainEditor.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { EditorContent } from '@tiptap/react';
import { BubbleMenu } from '@tiptap/react/menus';
import { Share, Trash2, AlignLeft, AlignCenter, AlignRight, Crop, RotateCw, FolderOpen, ChevronDown, Plus, X } from 'lucide-react';
import { Note } from '../lib/types';
import { useNoteEditor } from '../hooks/useNoteEditor';
import { useFolders } from '../hooks/useNotes';
import { EditorToolbar, ToolbarButton } from './editor/EditorToolbar';
import { StatusBadge } from './editor/StatusBadge';
import { ImageCropModal } from './editor/ImageCropModal';
import type { JSONContent } from '@tiptap/core';
import { normalizeUploadedImageUrl } from '../lib/utils';

interface MainEditorProps {
    note?: Note | null;
    onSave: (note: { title: string; content: JSONContent; tags?: string[]; folderId?: string | null }) => void;
    onDelete?: () => void;
    isPending: boolean;
}

export function MainEditor({ note, onSave, onDelete, isPending }: MainEditorProps) {
    const fileInputRef = useRef<HTMLInputElement>(null);
    const tagInputRef = useRef<HTMLInputElement>(null);
    const [cropImageInfo, setCropImageInfo] = useState<{ src: string; file: File } | null>(null);
    const [isTagComposerOpen, setIsTagComposerOpen] = useState(false);
    const createdAtDate = note?.createdAt ? new Date(note.createdAt) : null;
    const { data: folders = [] } = useFolders();

    // Everything complex is now hidden in this hook
    const {
        editor,
        title,
        tags,
        tagInput,
        folderId,
        saveStatus,
        handleTitleChange,
        handleTagInputChange,
        handleAddTag,
        handleRemoveTag,
        handleFolderChange,
        handleFileUpload,
        handleCrop,
        handleRotate
    } = useNoteEditor({ note, onSave, isPending });

    const selectedFolder = folders.find((folder) => folder.id === folderId) ?? null;

    useEffect(() => {
        if (!isTagComposerOpen) {
            return;
        }

        tagInputRef.current?.focus();
    }, [isTagComposerOpen]);

    useEffect(() => {
        setIsTagComposerOpen(false);
    }, [note?.id]);

    if (note === undefined) {
        return <EmptyState />;
    }

    const commitTagComposer = () => {
        const didAddTag = handleAddTag();
        setIsTagComposerOpen(false);
        return didAddTag;
    };

    const startRotate = async (degrees: number) => {
        if (!editor || saveStatus === 'rotating' || saveStatus === 'saving') return;
        const attrs = editor.getAttributes('image');
        if (attrs.src) {
            let fullUrl = normalizeUploadedImageUrl(attrs.src.split('?')[0]);
            if (!fullUrl.startsWith('http')) {
                const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
                fullUrl = baseUrl + (fullUrl.startsWith('/') ? '' : '/') + fullUrl;
            }

            try {
                const response = await fetch(fullUrl);
                const blob = await response.blob();
                const file = new File([blob], 'image-to-rotate.webp', { type: blob.type });
                handleRotate(file, degrees);
            } catch (e) {
                console.error('Failed to fetch image for rotating', e);
            }
        }
    };

    const startCrop = async () => {
        if (!editor) return;
        const attrs = editor.getAttributes('image');
        if (attrs.src) {
            // Ensure absolute URL
            let fullUrl = normalizeUploadedImageUrl(attrs.src.split('?')[0]);
            if (!fullUrl.startsWith('http')) {
                const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
                fullUrl = baseUrl + (fullUrl.startsWith('/') ? '' : '/') + fullUrl;
            }

            try {
                const response = await fetch(fullUrl);
                const blob = await response.blob();
                const file = new File([blob], 'image-to-crop.webp', { type: blob.type });
                setCropImageInfo({ src: attrs.src, file });
            } catch (e) {
                console.error('Failed to fetch image for cropping', e);
            }
        }
    };

    return (
        <div
            data-component="MainEditor"
            className="flex-1 flex flex-col h-full min-h-0 overflow-hidden relative paper-texture"
        >
            {/* CLEAN HEADER SECTION */}
            <header data-slot="header" className="editor-header">
                <EditorToolbar
                    editor={editor}
                    onAddImage={() => fileInputRef.current?.click()}
                />

                <div data-slot="header-actions" className="flex items-center gap-2 md:gap-3 ml-auto">
                    <StatusBadge status={saveStatus} createdAt={note?.createdAt} updatedAt={note?.updatedAt} />

                    <div data-slot="note-actions" className="flex items-center gap-1">
                        <ToolbarButton icon={<Share size={18} />} onClick={() => { }} title="Share" />
                        <ToolbarButton
                            icon={<Trash2 size={18} />}
                            onClick={() => {
                                if (onDelete && confirm('Are you sure?')) {
                                    onDelete();
                                }
                            }}
                            title="Delete"
                        />
                    </div>
                </div>
            </header>

            {/* SCROLLABLE CONTENT AREA */}
            <main data-slot="content-scroll" className="flex-1 overflow-y-auto scroll-smooth custom-scrollbar">
                <div data-slot="content-container" className="editor-content-container">
                    <span data-slot="created-at" className="date-label">
                        {createdAtDate
                            ? `${createdAtDate.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} at ${createdAtDate.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}`
                            : 'Draft'}
                    </span>

                    <input
                        data-slot="title-input"
                        type="text"
                        placeholder="Title"
                        value={title}
                        onChange={(e) => handleTitleChange(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && editor?.commands.focus()}
                        className="title-input transition-all focus:pl-1"
                    />

                    <div data-slot="metadata-row" className="mt-4 flex flex-wrap items-center gap-2.5">
                        <label
                            data-slot="folder-picker"
                            className="group relative inline-flex items-center gap-2 rounded-full border border-apple-border bg-white/70 dark:bg-white/5 px-3 py-2 text-sm text-gray-600 shadow-[0_10px_30px_rgba(15,23,42,0.05)] transition-colors hover:border-accent/25 hover:bg-white dark:hover:bg-white/8"
                        >
                            <FolderOpen size={14} className="text-gray-400 transition-colors group-hover:text-accent" />
                            <span className="pointer-events-none pr-4 font-medium text-gray-700 dark:text-gray-200">
                                {selectedFolder?.name ?? 'Add Folder'}
                            </span>
                            <ChevronDown size={14} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-gray-400" />
                            <select
                                value={folderId ?? ''}
                                onChange={(e) => handleFolderChange(e.target.value || null)}
                                className="absolute inset-0 cursor-pointer appearance-none rounded-full opacity-0"
                                aria-label="Select folder"
                            >
                                <option value="">No Folder</option>
                                {folders.map((folder) => (
                                    <option key={folder.id} value={folder.id}>
                                        {folder.name}
                                    </option>
                                ))}
                            </select>
                        </label>

                        <div data-slot="tag-list" className="flex flex-1 flex-wrap items-center gap-2 min-w-[240px]">
                            {tags.map((tag) => (
                                <button
                                    key={tag}
                                    data-slot="tag-chip"
                                    data-tag-name={tag}
                                    type="button"
                                    onClick={() => handleRemoveTag(tag)}
                                    className="group inline-flex items-center gap-1.5 rounded-full border border-apple-border bg-black/[0.03] px-3 py-1.5 text-xs font-semibold tracking-[0.02em] text-gray-600 transition-all hover:border-accent/30 hover:bg-accent/10 hover:text-gray-900 dark:bg-white/[0.06] dark:text-gray-200 dark:hover:bg-white/[0.10]"
                                    title={`Remove #${tag}`}
                                >
                                    <span>#{tag}</span>
                                    <X size={12} className="opacity-40 transition-opacity group-hover:opacity-100" />
                                </button>
                            ))}

                            {isTagComposerOpen ? (
                                <input
                                    ref={tagInputRef}
                                    data-slot="tag-input"
                                    type="text"
                                    placeholder="Add tag"
                                    value={tagInput}
                                    onChange={(e) => handleTagInputChange(e.target.value)}
                                    onBlur={() => commitTagComposer()}
                                    onKeyDown={(e) => {
                                        if (e.key === 'Enter' || e.key === ',') {
                                            e.preventDefault();
                                            commitTagComposer();
                                        }

                                        if (e.key === 'Escape') {
                                            e.preventDefault();
                                            handleTagInputChange('');
                                            setIsTagComposerOpen(false);
                                        }
                                    }}
                                    className="min-w-[132px] rounded-full border border-dashed border-apple-border bg-transparent px-3 py-1.5 text-sm text-gray-700 outline-none transition-colors placeholder:text-gray-400 focus:border-accent/40 dark:text-gray-200"
                                />
                            ) : (
                                <button
                                    type="button"
                                    data-slot="tag-add-button"
                                    onClick={() => setIsTagComposerOpen(true)}
                                    className="inline-flex items-center gap-1.5 rounded-full border border-dashed border-apple-border bg-transparent px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-gray-400 transition-colors hover:border-accent/30 hover:text-accent"
                                >
                                    <Plus size={12} />
                                    {tags.length > 0 ? 'Tag' : 'Add Tag'}
                                </button>
                            )}
                        </div>
                    </div>

                    <div data-slot="editor-body" className="min-h-[60vh] prose-container">
                        {editor && (
                            <BubbleMenu editor={editor} shouldShow={({ editor }) => editor.isActive('image')}>
                                <div data-slot="image-bubble-menu" className="flex items-center p-1 bg-white dark:bg-zinc-900 border border-apple-border rounded-xl shadow-xl gap-0.5 glass">
                                    <ToolbarButton icon={<AlignLeft size={16} />} onClick={() => editor.chain().focus().setTextAlign('left').run()} active={editor.isActive({ textAlign: 'left' })} title="Align Left" />
                                    <ToolbarButton icon={<AlignCenter size={16} />} onClick={() => editor.chain().focus().setTextAlign('center').run()} active={editor.isActive({ textAlign: 'center' })} title="Align Center" />
                                    <ToolbarButton icon={<AlignRight size={16} />} onClick={() => editor.chain().focus().setTextAlign('right').run()} active={editor.isActive({ textAlign: 'right' })} title="Align Right" />
                                    <div className="w-px h-4 mx-1 bg-apple-border" />
                                    <ToolbarButton icon={<RotateCw size={16} />} onClick={() => startRotate(90)} title="Rotate 90°" />
                                    <ToolbarButton icon={<Crop size={16} />} onClick={startCrop} title="Crop Image" />
                                </div>
                            </BubbleMenu>
                        )}
                        <EditorContent data-slot="editor-content" editor={editor} />
                    </div>
                </div>
            </main>

            {/* MODALS & HIDDEN INPUTS */}
            {cropImageInfo && (
                <ImageCropModal
                    imageUrl={cropImageInfo.src}
                    onCancel={() => setCropImageInfo(null)}
                    onCrop={(pixelCrop) => {
                        handleCrop(cropImageInfo.file, pixelCrop);
                        setCropImageInfo(null);
                    }}
                />
            )}
            <input
                type="file"
                ref={fileInputRef}
                className="hidden"
                accept="image/*"
                onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) handleFileUpload(file);
                    e.target.value = '';
                }}
            />
        </div>
    );
}

function EmptyState() {
    return (
        <div className="flex-1 flex flex-col items-center justify-center p-12 text-center space-y-8 paper-texture">
            <div className="relative">
                <div className="absolute inset-0 bg-accent/20 blur-3xl rounded-full" />
                <div className="relative w-32 h-32 bg-zinc-100 dark:bg-zinc-800 rounded-[3rem] flex items-center justify-center shadow-2xl backdrop-blur-sm border border-apple-border">
                    <span className="text-6xl drop-shadow-md">📒</span>
                </div>
            </div>
            <div className="space-y-3 max-w-sm">
                <h3 className="text-3xl font-bold tracking-tight italic">Notes</h3>
                <p className="text-zinc-500 font-medium">
                    Select a note from the sidebar to start writing, or capture a new thought.
                </p>
            </div>
        </div>
    );
}
