// front/src/components/editor/extensions/ImageResize.tsx

import { NodeViewWrapper, NodeViewProps } from '@tiptap/react';
import React, { useState, useRef, useEffect } from 'react';

export default function ImageResize(props: NodeViewProps) {
    const { node, updateAttributes, selected } = props;
    const [isResizing, setIsResizing] = useState(false);
    const [aspectRatio, setAspectRatio] = useState(1);
    const imgRef = useRef<HTMLImageElement>(null);

    useEffect(() => {
        if (imgRef.current) {
            const { naturalWidth, naturalHeight } = imgRef.current;
            if (naturalWidth && naturalHeight) {
                setAspectRatio(naturalWidth / naturalHeight);
            }
        }
    }, [node.attrs.src]);

    const handleResize = (e: MouseEvent) => {
        if (!isResizing || !imgRef.current) return;

        const rect = imgRef.current.getBoundingClientRect();
        const newWidth = e.clientX - rect.left;

        // Minimum width 50px
        if (newWidth < 50) return;

        updateAttributes({
            width: newWidth,
            height: newWidth / aspectRatio,
        });
    };

    const stopResize = () => {
        setIsResizing(false);
        document.removeEventListener('mousemove', handleResize);
        document.removeEventListener('mouseup', stopResize);
    };

    const startResize = (e: React.MouseEvent) => {
        e.preventDefault();
        setIsResizing(true);
        document.addEventListener('mousemove', handleResize);
        document.addEventListener('mouseup', stopResize);
    };

    return (
        <NodeViewWrapper className="relative inline-block group">
            <div className={`relative inline-block transition-all duration-200 ${selected ? 'ring-2 ring-accent ring-offset-2 rounded-2xl' : ''}`}>
                <img
                    ref={imgRef}
                    src={node.attrs.src}
                    style={{
                        width: node.attrs.width || 'auto',
                        height: node.attrs.height || 'auto',
                        maxWidth: '100%',
                    }}
                    className="rounded-2xl border border-apple-border block shadow-sm"
                    onLoad={() => {
                        if (imgRef.current) {
                            setAspectRatio(imgRef.current.naturalWidth / imgRef.current.naturalHeight);
                        }
                    }}
                />

                {selected && (
                    <div
                        className="absolute bottom-[-6px] right-[-6px] w-4 h-4 bg-accent border-2 border-white rounded-full cursor-nwse-resize z-30 shadow-md transition-transform hover:scale-125"
                        onMouseDown={startResize}
                    />
                )}
            </div>
        </NodeViewWrapper>
    );
}

// front/components/editor/extensions/ImageResize.vue
<script setup lang="ts">
import { NodeViewWrapper, type NodeViewProps } from '@tiptap/vue-3';

const props = defineProps<NodeViewProps>();

const imgRef = ref<HTMLImageElement | null>(null);
const isResizing = ref(false);
const aspectRatio = ref(1);

function updateAspectRatio() {
  if (!imgRef.value) return;

  const { naturalWidth, naturalHeight } = imgRef.value;
  if (naturalWidth && naturalHeight) {
    aspectRatio.value = naturalWidth / naturalHeight;
  }
}

function handleResize(event: MouseEvent) {
  if (!isResizing.value || !imgRef.value) return;

  const rect = imgRef.value.getBoundingClientRect();
  const newWidth = event.clientX - rect.left;
  if (newWidth < 50) return;

  props.updateAttributes({
    width: newWidth,
    height: newWidth / aspectRatio.value,
  });
}

function stopResize() {
  isResizing.value = false;
  document.removeEventListener('mousemove', handleResize);
  document.removeEventListener('mouseup', stopResize);
}

function startResize(event: MouseEvent) {
  event.preventDefault();
  isResizing.value = true;
  document.addEventListener('mousemove', handleResize);
  document.addEventListener('mouseup', stopResize);
}

onBeforeUnmount(stopResize);
watch(() => props.node.attrs.src, () => nextTick(updateAspectRatio));
</script>

<template>
  <NodeViewWrapper class="relative inline-block">
    <div class="relative inline-block rounded-md" :class="selected ? 'ring-2 ring-primary ring-offset-2 ring-offset-background' : ''">
      <img
        ref="imgRef"
        :src="node.attrs.src"
        :style="{
          width: node.attrs.width ? `${node.attrs.width}px` : 'auto',
          height: node.attrs.height ? `${node.attrs.height}px` : 'auto',
          maxWidth: '100%',
        }"
        class="block rounded-md border"
        @load="updateAspectRatio"
      >

      <div
        v-if="selected"
        class="absolute bottom-[-6px] right-[-6px] z-30 size-4 cursor-nwse-resize rounded-full border-2 border-background bg-primary shadow-sm transition-transform hover:scale-110"
        @mousedown="startResize"
      />
    </div>
  </NodeViewWrapper>
</template>
