// front/src/components/NoteCard.tsx
import { Note } from '../lib/types';
import { formatRelativeTime, stripHtml, extractFirstImage } from '../lib/utils';

interface NoteCardProps {
    note: Note;
    isActive?: boolean;
    onClick?: () => void;
    onDragStart?: (e: React.DragEvent<HTMLButtonElement>) => void;
}

export function NoteCard({ note, isActive, onClick, onDragStart }: NoteCardProps) {
    const snippet = stripHtml(note.content);
    const imageUrl = extractFirstImage(note.content);
    const visibleTags = (note.tags ?? []).slice(0, 3);

    return (
        <button
            type="button"
            draggable
            onClick={onClick}
            onDragStart={onDragStart}
            className={`group w-full text-left px-3.5 py-3.5 cursor-pointer transition-all relative rounded-2xl border ${isActive
                ? 'bg-apple-selection border-accent/35 shadow-sm'
                : 'border-transparent hover:bg-gray-100/70 dark:hover:bg-white/5 hover:border-apple-border/50'
                }`}
        >
            <div className="flex gap-3">
                <div className="flex-1 space-y-0.5 min-w-0">
                    <div className="flex justify-between items-baseline gap-2">
                        <h3 className="font-bold text-[14px] md:text-[15px] truncate text-gray-900 dark:text-gray-100">
                            {note.title || 'New Note'}
                        </h3>
                        {isActive && (
                            <div className="w-2.5 h-2.5 bg-accent rounded-full shadow-[0_0_8px_rgba(255,179,0,0.4)]" />
                        )}
                    </div>

                    <div className="flex items-center gap-1.5">
                        <span className="text-[11px] md:text-[12px] text-gray-400 whitespace-nowrap font-medium">
                            {formatRelativeTime(note.createdAt)}
                        </span>
                        <p className="text-[12px] md:text-[13px] text-gray-500 line-clamp-1 leading-snug">
                            {snippet || 'No additional text'}
                        </p>
                    </div>

                    {visibleTags.length > 0 && (
                        <div className="mt-2 flex flex-wrap gap-1.5">
                            {visibleTags.map((tag) => (
                                <span
                                    key={tag.id}
                                    className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-black/5 dark:bg-white/10 text-gray-600 dark:text-gray-300"
                                >
                                    {tag.name}
                                </span>
                            ))}
                        </div>
                    )}
                </div>

                {imageUrl && (
                    <div className="shrink-0 w-11 h-11 md:w-12 md:h-12 rounded-xl overflow-hidden border border-apple-border/50 bg-gray-50 bg-center bg-cover" style={{ backgroundImage: `url(${imageUrl})` }} />
                )}
            </div>

            {/* Inset Separator - only show if not active and last item handled by parent list */}
            {!isActive && (
                <div className="hidden md:block absolute bottom-0 right-0 left-4 h-px bg-apple-border" />
            )}
        </button>
    );
}

// front/components/NoteCard.vue
<script setup lang="ts">
import { FileText, GripVertical } from 'lucide-vue-next';
import { Badge } from '~/components/ui/badge';
import { extractFirstImage, formatRelativeTime, stripHtml } from '~/utils/notes';
import type { Note } from '~/types/notes';

const props = defineProps<{
  note: Note;
  isActive?: boolean;
}>();

const emit = defineEmits<{
  select: [note: Note];
  dragstart: [event: DragEvent, note: Note];
}>();

const isDragging = ref(false);

const snippet = computed(() => stripHtml(props.note.content));
const imageUrl = computed(() => extractFirstImage(props.note.content));
const visibleTags = computed(() => (props.note.tags ?? []).slice(0, 3));
const hiddenTagCount = computed(() => Math.max((props.note.tags?.length ?? 0) - visibleTags.value.length, 0));

function onDragStart(event: DragEvent) {
  isDragging.value = true;
  document.body.classList.add('is-dragging-note');
  emit('dragstart', event, props.note);
}

function onDragEnd() {
  isDragging.value = false;
  document.body.classList.remove('is-dragging-note');
}
</script>

<template>
  <div
    :data-note-id="note.id"
    draggable="true"
    class="group relative flex w-full min-w-0 cursor-grab rounded-md border bg-card p-3 text-left text-card-foreground transition-all duration-150 hover:bg-accent/60 active:cursor-grabbing"
    :class="[
      isActive ? 'border-primary bg-accent' : 'border-border',
      isDragging ? 'scale-[0.98] opacity-40 ring-2 ring-primary' : '',
    ]"
    role="button"
    tabindex="0"
    @click="emit('select', note)"
    @keydown.enter="emit('select', note)"
    @keydown.space.prevent="emit('select', note)"
    @dragstart="onDragStart"
    @dragend="onDragEnd"
  >
    <span
      class="absolute left-1 top-1/2 -translate-x-1 -translate-y-1/2 text-muted-foreground/0 transition-all duration-200 ease-out group-hover:translate-x-0 group-hover:text-muted-foreground/70"
      aria-hidden="true"
    >
      <GripVertical class="size-3.5" />
    </span>

    <div class="flex min-w-0 flex-1 items-start gap-3">
      <div class="transition-transform duration-200 ease-out group-hover:translate-x-3">
        <div
          v-if="imageUrl"
          class="size-11 shrink-0 rounded-md border bg-cover bg-center"
          :style="{ backgroundImage: `url(${imageUrl})` }"
        />
        <div v-else class="flex size-11 shrink-0 items-center justify-center rounded-md border bg-muted text-muted-foreground">
          <FileText class="size-4" />
        </div>
      </div>

      <div class="min-w-0 flex-1 space-y-1 transition-transform duration-200 ease-out group-hover:translate-x-3">
        <h3 class="truncate text-sm font-medium">
          {{ note.title || 'Untitled' }}
        </h3>
        <p class="line-clamp-2 text-xs leading-5 text-muted-foreground">
          {{ snippet || 'No additional text' }}
        </p>

        <div v-if="visibleTags.length > 0" class="flex flex-wrap gap-1 pt-1">
          <Badge v-for="tag in visibleTags" :key="tag.id" variant="secondary">
            {{ tag.name }}
          </Badge>
          <Badge v-if="hiddenTagCount > 0" variant="outline">
            +{{ hiddenTagCount }}
          </Badge>
        </div>
      </div>

      <span class="shrink-0 font-mono text-[11px] text-muted-foreground">
        {{ formatRelativeTime(note.updatedAt ?? note.createdAt) }}
      </span>
    </div>
  </div>
</template>
