// front/src/components/NoteList.tsx
import { Note } from '../lib/types';
import { NoteCard } from './NoteCard';
import { SearchIcon, XIcon } from 'lucide-react';

interface NoteListProps {
    notes?: Note[];
    isLoading: boolean;
    isError: boolean;
    selectedId?: string;
    onSelect: (note: Note) => void;
    searchQuery?: string;
    onClearSearch?: () => void;
}

export function NoteList({ notes, isLoading, isError, selectedId, onSelect, searchQuery, onClearSearch }: NoteListProps) {
    if (isLoading) {
        return (
            <div data-component="NoteListLoading" className="w-full md:w-84 border-b md:border-b-0 md:border-r border-apple-border h-full bg-white/80 dark:bg-black/20 overflow-hidden">
                <div data-slot="header-skeleton" className="px-4 md:pl-12 border-b border-apple-border flex items-center h-13">
                    <div className="h-6 bg-gray-100 dark:bg-white/5 rounded-lg animate-pulse w-full max-w-30" />
                </div>
                <div className="space-y-0">
                    {[1, 2, 3, 4, 5].map(i => (
                        <div key={i} className="px-4 py-3.5 border-b border-apple-border/50 animate-pulse flex gap-3">
                            <div className="flex-1 space-y-2">
                                <div className="h-3.5 bg-gray-100 dark:bg-white/5 rounded w-3/4" />
                                <div className="h-2.5 bg-gray-100 dark:bg-white/5 rounded w-1/2" />
                            </div>
                            <div className="w-10 h-10 bg-gray-100 dark:bg-white/5 rounded-lg" />
                        </div>
                    ))}
                </div>
            </div>
        );
    }

    if (isError) {
        return (
            <div data-component="NoteListError" className="w-full md:w-84 border-b md:border-b-0 md:border-r border-apple-border h-full flex items-center justify-center p-8 text-center bg-white/80 dark:bg-black/20 paper-texture">
                <p className="text-sm text-red-500 font-medium">Failed to load notes.</p>
            </div>
        );
    }

    const hasSearchQuery = searchQuery && searchQuery.trim().length > 0;
    const showNoResults = hasSearchQuery && notes && notes.length === 0;

    return (
        <div data-component="NoteList" className="w-full md:w-84 flex flex-col border-b md:border-b-0 md:border-r border-apple-border h-full bg-white/85 dark:bg-black/20 overflow-hidden">
            {/* Note List Header */}
            <div data-slot="header" className="h-13 px-4 flex items-center justify-between border-b border-apple-border/50 bg-white/70 dark:bg-black/5 backdrop-blur-md">
                <div data-slot="header-title" className="flex items-center gap-2">
                    {hasSearchQuery && (
                        <SearchIcon size={14} className="text-gray-400" />
                    )}
                    <h2 className="text-[11px] md:text-[13px] font-bold text-gray-400 uppercase tracking-widest pl-1 md:pl-2">
                        {hasSearchQuery ? 'Search Results' : 'Notes'}
                    </h2>
                </div>
                <div data-slot="header-actions" className="flex items-center gap-2">
                    <div data-slot="count" className="px-2 py-0.5 rounded-md bg-black/5 dark:bg-white/5 text-[11px] font-bold text-gray-500">
                        {notes?.length || 0}
                    </div>
                    {hasSearchQuery && onClearSearch && (
                        <button
                            data-slot="clear-search"
                            onClick={onClearSearch}
                            className="p-1 hover:bg-black/5 dark:hover:bg-white/5 rounded transition-colors"
                        >
                            <XIcon size={12} className="text-gray-400" />
                        </button>
                    )}
                </div>
            </div>

            <div data-slot="list-scroll" className="flex-1 overflow-y-auto overflow-x-hidden px-2 pt-2 pb-24 md:px-2 md:pb-12">
                {showNoResults ? (
                    <div data-slot="empty-search" className="p-8 md:p-12 text-center space-y-3 opacity-40">
                        <div className="text-4xl">🔍</div>
                        <p className="text-[14px] font-bold text-gray-500 italic">No results found</p>
                        <p className="text-[12px] text-gray-400">
                            Try a different search term
                        </p>
                    </div>
                ) : notes?.length === 0 ? (
                    <div data-slot="empty-list" className="p-8 md:p-12 text-center space-y-3 opacity-40">
                        <div className="text-4xl">📭</div>
                        <p className="text-[14px] font-bold text-gray-500 italic">No Notes</p>
                    </div>
                ) : (
                    <div data-slot="list" className="space-y-1.5 md:space-y-0.5">
                        {notes?.map((note) => (
                            <NoteCard
                                key={note.id}
                                note={note}
                                isActive={selectedId === note.id}
                                onClick={() => onSelect(note)}
                                onDragStart={(e) => {
                                    e.dataTransfer.effectAllowed = 'move';
                                    e.dataTransfer.setData('text/plain', note.id);
                                }}
                            />
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}

// front/components/NoteList.vue
<script setup lang="ts">
import { AlertTriangle, FileText, LayoutGrid, List, SearchX, X } from 'lucide-vue-next';
import { Button } from '~/components/ui/button';
import { Skeleton } from '~/components/ui/skeleton';
import type { Note } from '~/types/notes';

const props = withDefaults(defineProps<{
  notes?: Note[];
  isLoading: boolean;
  isError: boolean;
  selectedId?: string;
  searchQuery?: string;
  viewMode?: 'list' | 'grid';
  title?: string;
}>(), {
  notes: () => [],
  selectedId: '',
  searchQuery: '',
  viewMode: 'list',
  title: 'Notes',
});

const emit = defineEmits<{
  select: [note: Note];
  clearSearch: [];
  'update:viewMode': [mode: 'list' | 'grid'];
}>();

const hasSearchQuery = computed(() => props.searchQuery.trim().length > 0);
const showNoResults = computed(() => hasSearchQuery.value && props.notes.length === 0);

function handleDragStart(event: DragEvent, note: Note) {
  if (!event.dataTransfer) return;

  event.dataTransfer.effectAllowed = 'move';
  event.dataTransfer.setData('text/plain', note.id);
}
</script>

<template>
  <section class="flex h-full min-h-0 flex-col">
    <div class="flex min-h-12 items-center justify-between border-b px-4">
      <div class="min-w-0">
        <h2 class="text-sm font-medium">
          {{ hasSearchQuery ? 'Search results' : title }}
        </h2>
        <p class="font-mono text-[11px] text-muted-foreground">
          {{ notes.length }} item{{ notes.length === 1 ? '' : 's' }}
        </p>
      </div>
      <div class="flex items-center gap-2">
        <div class="flex rounded-md border bg-background p-0.5">
          <Button
            variant="ghost"
            size="icon"
            :class="viewMode === 'list' ? 'bg-accent' : ''"
            :aria-pressed="viewMode === 'list'"
            aria-label="List view"
            @click="emit('update:viewMode', 'list')"
          >
            <List class="size-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            :class="viewMode === 'grid' ? 'bg-accent' : ''"
            :aria-pressed="viewMode === 'grid'"
            aria-label="Grid view"
            @click="emit('update:viewMode', 'grid')"
          >
            <LayoutGrid class="size-4" />
          </Button>
        </div>
        <Button
          v-if="hasSearchQuery"
          variant="ghost"
          size="icon"
          aria-label="Clear search"
          @click="emit('clearSearch')"
        >
          <X class="size-4" />
        </Button>
      </div>
    </div>

    <div class="min-h-0 flex-1 overflow-y-auto p-3 scrollbar-thin">
      <div v-if="isLoading" class="space-y-2">
        <Skeleton v-for="i in 6" :key="i" class="h-20 w-full" />
      </div>

      <EmptyState
        v-else-if="isError"
        :icon="AlertTriangle"
        title="Failed to load notes"
        description="Refresh the page or try again in a moment."
      />

      <EmptyState
        v-else-if="showNoResults"
        :icon="SearchX"
        title="No results found"
        description="Try a different search term or clear the current query."
      >
        <Button variant="outline" size="sm" @click="emit('clearSearch')">
          Clear search
        </Button>
      </EmptyState>

      <EmptyState
        v-else-if="notes.length === 0"
        :icon="FileText"
        title="No notes yet"
        description="Create your first note to start the workspace."
      />

      <div
        v-else
        :class="viewMode === 'grid'
          ? 'grid grid-cols-1 gap-3 lg:grid-cols-2 2xl:grid-cols-3'
          : 'space-y-2'"
      >
        <NoteCard
          v-for="note in notes"
          :key="note.id"
          :note="note"
          :is-active="selectedId === note.id"
          @select="emit('select', note)"
          @dragstart="handleDragStart"
        />
      </div>
    </div>
  </section>
</template>
