// front/src/components/editor/EditorToolbar.tsx

import React from 'react';
import { Editor } from '@tiptap/react';
import {
    Bold,
    Italic,
    List,
    CheckSquare,
    Image as ImageIcon,
    Table as TableIcon
} from 'lucide-react';

interface ToolbarButtonProps {
    icon: React.ReactNode;
    onClick: () => void;
    active?: boolean;
    title?: string;
}

export function ToolbarButton({ icon, onClick, active = false, title }: ToolbarButtonProps) {
    return (
        <button
            onClick={onClick}
            title={title}
            className={`w-8.5 h-8 md:w-9.5 md:h-8 flex items-center justify-center rounded-lg transition-all duration-200 
                ${active ? 'bg-white shadow-sm border-apple-border text-accent dark:bg-zinc-800' : 'text-zinc-500 hover:text-zinc-900 border-transparent hover:bg-zinc-100 dark:hover:bg-zinc-800'}`}
            style={{ border: '1px solid currentColor', borderColor: active ? 'var(--border)' : 'transparent' }}
        >
            {icon}
        </button>
    );
}

interface EditorToolbarProps {
    editor: Editor | null;
    onAddImage: () => void;
}

export function EditorToolbar({ editor, onAddImage }: EditorToolbarProps) {
    if (!editor) return null;

    const handleTableAction = () => {
        if (editor.isActive('table')) {
            editor.chain().focus().addRowAfter().run();
        } else {
            editor.chain().focus().insertTable({ rows: 2, cols: 2, withHeaderRow: true }).run();
        }
    };

    return (
        <div className="flex items-center gap-1.5 p-1 overflow-x-auto max-w-full">
            <div className="toolbar-group">
                <ToolbarButton
                    icon={<CheckSquare size={17} strokeWidth={2.5} />}
                    onClick={() => editor.chain().focus().toggleTaskList().run()}
                    active={editor.isActive('taskList')}
                    title="Checklist"
                />
                <ToolbarButton
                    icon={<List size={17} strokeWidth={2.5} />}
                    onClick={() => editor.chain().focus().toggleBulletList().run()}
                    active={editor.isActive('bulletList')}
                    title="Bullet List"
                />
                <ToolbarButton
                    icon={<TableIcon size={17} strokeWidth={2.5} />}
                    onClick={handleTableAction}
                    active={editor.isActive('table')}
                    title={editor.isActive('table') ? "Add Row" : "Table"}
                />
            </div>

            <div className="w-px h-5 mx-1.5 bg-apple-border/50" />

            <div className="toolbar-group">
                <ToolbarButton
                    icon={<Bold size={17} strokeWidth={2.5} />}
                    onClick={() => editor.chain().focus().toggleBold().run()}
                    active={editor.isActive('bold')}
                    title="Bold"
                />
                <ToolbarButton
                    icon={<Italic size={17} strokeWidth={2.5} />}
                    onClick={() => editor.chain().focus().toggleItalic().run()}
                    active={editor.isActive('italic')}
                    title="Italic"
                />
            </div>

            <div className="w-px h-5 mx-1.5 bg-apple-border/50" />

            <ToolbarButton
                icon={<ImageIcon size={18} strokeWidth={2} />}
                onClick={onAddImage}
                title="Add Image"
            />
        </div>
    );
}

// front/components/editor/EditorToolbar.vue
<script setup lang="ts">
import type { Editor } from '@tiptap/core';
import { Bold, CheckSquare, Image as ImageIcon, Italic, List, Table as TableIcon } from 'lucide-vue-next';
import type { Component } from 'vue';
import { Button } from '~/components/ui/button';

const props = defineProps<{
  editor: Editor | null;
}>();

const emit = defineEmits<{
  addImage: [];
}>();

type ToolItem = {
  label: string;
  icon: Component;
  active?: () => boolean;
  action: () => void;
};

const insertTools = computed<ToolItem[]>(() => [
  {
    label: 'Checklist',
    icon: CheckSquare,
    active: () => props.editor?.isActive('taskList') ?? false,
    action: () => props.editor?.chain().focus().toggleTaskList().run(),
  },
  {
    label: 'Bullet list',
    icon: List,
    active: () => props.editor?.isActive('bulletList') ?? false,
    action: () => props.editor?.chain().focus().toggleBulletList().run(),
  },
  {
    label: props.editor?.isActive('table') ? 'Add table row' : 'Table',
    icon: TableIcon,
    active: () => props.editor?.isActive('table') ?? false,
    action: handleTableAction,
  },
]);

const formatTools = computed<ToolItem[]>(() => [
  {
    label: 'Bold',
    icon: Bold,
    active: () => props.editor?.isActive('bold') ?? false,
    action: () => props.editor?.chain().focus().toggleBold().run(),
  },
  {
    label: 'Italic',
    icon: Italic,
    active: () => props.editor?.isActive('italic') ?? false,
    action: () => props.editor?.chain().focus().toggleItalic().run(),
  },
]);

function handleTableAction() {
  if (!props.editor) return;

  if (props.editor.isActive('table')) {
    props.editor.chain().focus().addRowAfter().run();
  } else {
    props.editor.chain().focus().insertTable({ rows: 2, cols: 2, withHeaderRow: true }).run();
  }
}

function toolVariant(tool: ToolItem) {
  return tool.active?.() ? 'secondary' : 'ghost';
}
</script>

<template>
  <div v-if="editor" class="flex max-w-full items-center gap-1 overflow-x-auto rounded-md border bg-background p-1 scrollbar-thin">
    <div class="flex items-center gap-1">
      <Button
        v-for="tool in insertTools"
        :key="tool.label"
        :variant="toolVariant(tool)"
        size="icon"
        :title="tool.label"
        @click="tool.action"
      >
        <component :is="tool.icon" class="size-4" />
      </Button>
    </div>

    <div class="mx-1 h-5 w-px bg-border" />

    <div class="flex items-center gap-1">
      <Button
        v-for="tool in formatTools"
        :key="tool.label"
        :variant="toolVariant(tool)"
        size="icon"
        :title="tool.label"
        @click="tool.action"
      >
        <component :is="tool.icon" class="size-4" />
      </Button>
    </div>

    <div class="mx-1 h-5 w-px bg-border" />

    <Button
      variant="ghost"
      size="icon"
      title="Add image"
      @click="emit('addImage')"
    >
      <ImageIcon class="size-4" />
    </Button>
  </div>
</template>
