// front/src/components/editor/StatusBadge.tsx

import React from 'react';
import { SaveStatus } from '../../hooks/useNoteEditor';
import { formatRelativeTime } from '../../lib/utils';

interface StatusBadgeProps {
    status: SaveStatus;
    createdAt?: string;
    updatedAt?: string;
}

export function StatusBadge({ status, createdAt, updatedAt }: StatusBadgeProps) {
    if (status === 'idle') {
        return (
            <div className="status-badge opacity-60">
                <span>{updatedAt ? `Updated ${formatRelativeTime(updatedAt)}` : createdAt ? formatRelativeTime(createdAt) : 'Draft'}</span>
            </div>
        );
    }

    return (
        <div className="status-badge">
            {(status === 'saving' || status === 'optimizing') && (
                <span className="w-1.5 h-1.5 rounded-full bg-accent animate-pulse" />
            )}
            <span className="text-accent/80 transition-colors duration-300">
                {status === 'optimizing' ? 'Optimizing (WASM)' :
                    status === 'cropping' ? 'Cropping Image (WASM)' :
                        status === 'saving' ? 'Saving' :
                            status === 'saved' ? 'Saved' : ''}
            </span>
        </div>
    );
}

// front/components/editor/StatusBadge.vue
<script setup lang="ts">
import type { SaveStatus } from '~/composables/useNoteEditor';
import { formatRelativeTime } from '~/utils/notes';

const props = defineProps<{
  status: SaveStatus;
  createdAt?: string;
  updatedAt?: string;
}>();

const idleLabel = computed(() => {
  if (props.updatedAt) return `Updated ${formatRelativeTime(props.updatedAt)}`;
  if (props.createdAt) return formatRelativeTime(props.createdAt);
  return 'Draft';
});

const statusLabel = computed(() => {
  if (props.status === 'optimizing') return 'Optimizing';
  if (props.status === 'cropping') return 'Cropping';
  if (props.status === 'rotating') return 'Rotating';
  if (props.status === 'saving') return 'Saving';
  if (props.status === 'saved') return 'Saved';
  return idleLabel.value;
});

const dotClass = computed(() => {
  if (props.status === 'saved') return 'bg-primary';
  if (props.status === 'idle') return 'bg-muted-foreground';
  return 'animate-pulse bg-primary';
});
</script>

<template>
  <div class="inline-flex h-7 items-center gap-2 rounded-md border px-2.5 font-mono text-[11px] text-muted-foreground">
    <span class="size-1.5 rounded-full" :class="dotClass" />
    <span>{{ statusLabel }}</span>
  </div>
</template>
